#!/usr/bin/env python3
"""
AI-powered test generator - codebase analyze karke automatically tests generate karta hai.
"""
import os
import sys
import json
from pathlib import Path
from openai import OpenAI

# OpenAI client initialize
api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    print("Error: OPENAI_API_KEY environment variable set nahi hai!")
    sys.exit(1)

client = OpenAI(api_key=api_key)

def read_codebase():
    """Sab code files read karke return karta hai."""
    codebase = {}
    project_root = Path(__file__).parent.parent
    
    # Important files/folders scan karo
    paths_to_scan = [
        "app/**/*.py",
        "*.py",
    ]
    
    for pattern in paths_to_scan:
        for file_path in project_root.glob(pattern):
            if file_path.is_file() and "__pycache__" not in str(file_path):
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        relative_path = file_path.relative_to(project_root)
                        codebase[str(relative_path)] = f.read()
                except Exception as e:
                    print(f"Warning: {file_path} read nahi ho paya: {e}")
    
    return codebase

def generate_tests_with_ai(codebase_content):
    """AI se comprehensive test cases generate karta hai."""
    
    codebase_str = "\n\n".join([
        f"=== {file} ===\n{content}"
        for file, content in codebase_content.items()
    ])
    
    prompt = f"""Tum ek senior Python test engineer ho. Neeche diya gaya codebase analyze karo aur comprehensive test cases generate karo.

**Codebase:**
{codebase_str}

**Requirements:**
1. FastAPI application ke liye pytest tests likho
2. Har endpoint, function, aur edge case ko cover karo
3. Positive cases, negative cases, boundary conditions sab test karo
4. Test names descriptive aur clear honi chahiye
5. FastAPI TestClient use karo
6. Code quality: proper assertions, error handling, edge cases

**Output Format:**
Sirf Python test code output karo, koi explanation mat do. File ka complete code do jo directly tests/test_swap_api.py mein save ho sakta hai.

Example structure:
```python
import pytest
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

# Tests here...
```

Ab complete test file generate karo:"""

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",  # Cost-effective, fast
            messages=[
                {"role": "system", "content": "Tum ek expert Python test engineer ho. Sirf valid Python test code output karo, koi explanation mat do."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,  # Consistent output ke liye
            max_tokens=2000
        )
        
        generated_code = response.choices[0].message.content.strip()
        
        # Code block se extract karo agar ```python ... ``` format mein hai
        if "```python" in generated_code:
            generated_code = generated_code.split("```python")[1].split("```")[0].strip()
        elif "```" in generated_code:
            generated_code = generated_code.split("```")[1].split("```")[0].strip()
        
        return generated_code
        
    except Exception as e:
        print(f"Error: AI se tests generate nahi ho paye: {e}")
        sys.exit(1)

def save_tests(test_code, output_file):
    """Generated tests ko file mein save karta hai."""
    output_path = Path(__file__).parent.parent / output_file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Header add karo
    header = '''"""
AI-generated tests - automatically generated by AI test generator.
Do not edit manually - yeh file har push par regenerate hoti hai.
"""
'''
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("\n")
        f.write(test_code)
        f.write("\n")
    
    print(f"✅ Tests successfully generated aur save ho gaye: {output_file}")

def main():
    print("🔍 Codebase scan kar raha hoon...")
    codebase = read_codebase()
    
    if not codebase:
        print("❌ Koi code files nahi mili!")
        sys.exit(1)
    
    print(f"📁 {len(codebase)} files scan kiye:")
    for file in codebase.keys():
        print(f"   - {file}")
    
    print("\n🤖 AI se tests generate kar raha hoon...")
    test_code = generate_tests_with_ai(codebase)
    
    print("\n💾 Tests save kar raha hoon...")
    save_tests(test_code, "tests/test_swap_api.py")
    
    print("\n✅ Test generation complete!")

if __name__ == "__main__":
    main()
